### ISSUE TITLE
Can I use in my opensource project ?

### ISSUE THREAD

**Issue by dhanababum** [gordthompson/msaccessdb#1]
Hi Thompson,

   I found this package is very interesting, Creating access database is very easy using your package. Can I use your package in my opensource project.

Regards,
Dhana Babu

**Comment by gordthompson** [comment]
Certainly. For details on the conditions under which you can to that, refer to the LICENSE:

https://github.com/gordthompson/msaccessdb/blob/master/LICENSE

Good luck with your project!
